#!/bin/bash

#remove the old files
rm -rf bin/*

#compile with jar files
#javac -d bin -sourcepath src -cp lib/lib1.jar; lib/lib2.jar src/App.java src/player/*.java src/ui/*.java

# the files and compilation#
javac -d bin -sourcepath src -cp lib/jl1.0.1.jar src/App.java src/player/*.java src/ui/*.java

cp lib/jl1.0.1.jar bin

#change directory
cd bin
#run
java App -cp lib/jl1.0.1.jar